"""jwt authentication method

Revision ID: f93d9ec7ed14
Revises: f1bfbf53236b
Create Date: 2022-02-22 23:27:09.329207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93d9ec7ed14'
down_revision = 'f1bfbf53236b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=511), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
